# Generated by Django 4.0.5 on 2022-07-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='이벤트 제목')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/product/', verbose_name='썸네일')),
                ('introduction', models.CharField(max_length=200, verbose_name='설명')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='등록일자')),
                ('started_at', models.DateTimeField(verbose_name='노출시작일')),
                ('ended_at', models.DateTimeField(verbose_name='노출종료일')),
                ('activate', models.BooleanField(verbose_name='활성화여부')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='상품이름')),
                ('product_img', models.ImageField(blank=True, upload_to='images/product/', verbose_name='상품이미지')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('uploaded_at', models.DateField(auto_now_add=True, verbose_name='상품업로드날짜')),
                ('category', models.ManyToManyField(to='review.category', verbose_name='카테고리')),
            ],
        ),
    ]
