# Generated by Django 4.0.5 on 2022-06-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='이벤트 제목')),
                ('preview', models.CharField(max_length=100, verbose_name='미리보기')),
                ('introduction', models.CharField(max_length=200, verbose_name='설명')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='등록일자')),
                ('started_at', models.DateField(auto_now=True, verbose_name='노출시작일')),
                ('ended_at', models.DateField(auto_now=True, verbose_name='노출종료일')),
                ('activate', models.BooleanField(verbose_name='활성화여부')),
            ],
        ),
    ]
