# Generated by Django 4.0.5 on 2022-07-05 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 이름')),
                ('introduction', models.TextField(verbose_name='설명')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='상품이름')),
                ('product_img', models.ImageField(blank=True, upload_to='images/product/', verbose_name='상품이미지')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('uploaded_at', models.DateField(auto_now_add=True, verbose_name='상품업로드날짜')),
                ('started_at', models.DateTimeField(verbose_name='노출시작일')),
                ('ended_at', models.DateTimeField(verbose_name='노출종료일')),
                ('category', models.ManyToManyField(to='product.category', verbose_name='카테고리')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='게시인')),
            ],
        ),
    ]
