# Generated by Django 4.0.5 on 2022-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ended_at',
            field=models.DateField(verbose_name='노출종료일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='started_at',
            field=models.DateField(verbose_name='노출시작일'),
        ),
    ]
