# Generated by Django 4.0.5 on 2022-06-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='preview',
            field=models.FileField(blank=True, upload_to='product/files/%Y/%m/%d/', verbose_name='썸네일'),
        ),
    ]
