# Generated by Django 4.0.5 on 2022-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_event_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ended_at',
            field=models.DateTimeField(verbose_name='노출종료일'),
        ),
        migrations.AlterField(
            model_name='event',
            name='started_at',
            field=models.DateTimeField(verbose_name='노출시작일'),
        ),
    ]
