# Generated by Django 4.0.5 on 2022-07-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_ended_at_alter_product_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='images/product/', verbose_name='상품이미지'),
        ),
    ]
