# Generated by Django 4.0.5 on 2022-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_event_ended_at_alter_event_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='preview',
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='products/images/', verbose_name='썸네일'),
        ),
    ]
