# Generated by Django 4.0.5 on 2022-06-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_event_preview_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/product/', verbose_name='썸네일'),
        ),
    ]
