# Generated by Django 4.0.5 on 2022-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='카테고리 이름')),
                ('introduction', models.TextField(verbose_name='설명')),
            ],
        ),
    ]
