# Generated by Django 4.0.5 on 2022-06-14 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='글제목')),
                ('contents', models.TextField(verbose_name='글내용')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='작성날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='글작성자')),
                ('category', models.ManyToManyField(to='blog.category', verbose_name='카테고리')),
            ],
        ),
    ]
