# Generated by Django 4.0.5 on 2022-07-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 이름')),
                ('introduction', models.TextField(verbose_name='설명')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
