# Generated by Django 4.0.5 on 2022-07-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_alter_product_category'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
