# Generated by Django 4.0.5 on 2022-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='update_check',
            field=models.BooleanField(default=False, verbose_name='리뷰수정여부'),
        ),
    ]
