# Generated by Django 4.0.5 on 2022-07-05 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_category_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='평점')),
                ('contents', models.TextField(verbose_name='리뷰내용')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='리뷰작성날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='게시물작성자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
            ],
        ),
    ]
