# Generated by Django 4.0.5 on 2022-06-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자이름')),
                ('password', models.CharField(max_length=250, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=100, verbose_name='닉네임')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='가입날짜')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('introduction', models.CharField(max_length=300, verbose_name='소개글')),
            ],
        ),
    ]
