# Generated by Django 4.0.5 on 2022-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사용자이름')),
                ('password', models.CharField(max_length=250, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=100, verbose_name='닉네임')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='가입날짜')),
            ],
        ),
    ]
